services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: dataregistry
      MYSQL_DATABASE: bio
      MYSQL_USER: dataregistry
      MYSQL_PASSWORD: dataregistry
    command: ["--local-infile=1"]
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pdataregistry"]
      interval: 3s
      retries: 20
