name: example
envs:
  qa:
    BIOINDEX_S3_BUCKET: REPLACE_ME
    BIOINDEX_RDS_SECRET: REPLACE_ME    # or RDS_INSTANCE + USERNAME + PASSWORD
    BIOINDEX_BIO_SCHEMA: REPLACE_ME
  prod:
    BIOINDEX_S3_BUCKET: REPLACE_ME
    BIOINDEX_RDS_SECRET: REPLACE_ME
    BIOINDEX_BIO_SCHEMA: REPLACE_ME
