#!/bin/bash

env_file="${1:-.bioindex}"

./automation/compress.sh metabolomics-disease bioindex-dev/MetabolomicsWorkbench/disease/ $env_file
./automation/compress.sh gtex-sldsc bioindex-dev/GTEx/sldsc/mondo/ $env_file
./automation/compress.sh 4dn-gene bioindex-dev/4DN/gene/ $env_file
./automation/compress.sh 4dn-mondo bioindex-dev/4DN/mondo/ $env_file
./automation/compress.sh gtex-tstat bioindex-dev/GTEx/tstat/ $env_file
./automation/compress.sh 4dn-gene bioindex-dev/4DN/gene-bio/ $env_file
./automation/compress.sh 4dn-mondo bioindex-dev/4DN/mondo-bio/ $env_file
./automation/compress.sh exrna-gene-counts bioindex-dev/exRNA/gene-counts/ $env_file
./automation/compress.sh exrna-rbp-counts bioindex-dev/exRNA/rbp-counts/ $env_file
./automation/compress.sh lincs-corr bioindex-dev/lincs/corr/ $env_file
./automation/compress.sh diff-exp bioindex-dev/combined_diff_exp/gene/ $env_file
./automation/compress.sh diff-exp-phenotype bioindex-dev/combined_diff_exp/phenotype/ $env_file
./automation/compress.sh diff-exp-tissue bioindex-dev/combined_diff_exp/tissue/ $env_file
./automation/compress.sh pigean-gene-set-phenotype bioindex-dev/catalog/pigean/gene_set/phenotype/ $env_file
./automation/compress.sh pigean-gene-set bioindex-dev/catalog/pigean/gene_set/gene_set/ $env_file
./automation/compress.sh pigean-gene-phenotype bioindex-dev/catalog/pigean/gene/phenotype/ $env_file
./automation/compress.sh pigean-gene bioindex-dev/catalog/pigean/gene/gene/ $env_file
./automation/compress.sh pigean-joined-gene bioindex-dev/catalog/pigean/gene_gene_set/gene/ $env_file
./automation/compress.sh pigean-joined-gene-set bioindex-dev/catalog/pigean/gene_gene_set/gene_set/ $env_file
./automation/compress.sh diff-exp-phenotype-tissue bioindex-dev/combined_diff_exp/phenotype-tissue/ $env_file
./automation/compress.sh diff-exp-top-phenotype bioindex-dev/combined_diff_exp/top-phenotype/ $env_file
./automation/compress.sh diff-exp-top-tissue bioindex-dev/combined_diff_exp/top-tissue/ $env_file
./automation/compress.sh pigean-overall-gene bioindex-dev/catalog/pigean/gene_gene_set/overall_gene/ $env_file
./automation/compress.sh pigean-gene-set-source bioindex-dev/catalog/pigean/gene_set/source/ $env_file
./automation/compress.sh single-cell-lognorm bioindex-dev/hubmap/single_cell/gene_lognorm/ $env_file
./automation/compress.sh diff-exp-top-tissue-phenotype-source bioindex-dev/combined_diff_exp/top-tissue-phenotype-source/ $env_file
./automation/compress.sh kids-first-gene-variants bioindex-dev/KidsFirst/variants/gene2/ $env_file
./automation/compress.sh glygen-genes bioindex-dev/glygen/glygen/ $env_file

./automation/index.sh metabolomics-disease bioindex-dev/MetabolomicsWorkbench/disease/ $env_file
./automation/index.sh gtex-sldsc bioindex-dev/GTEx/sldsc/mondo/ $env_file
./automation/index.sh 4dn-gene bioindex-dev/4DN/gene/ $env_file
./automation/index.sh 4dn-mondo bioindex-dev/4DN/mondo/ $env_file
./automation/index.sh gtex-tstat bioindex-dev/GTEx/tstat/ $env_file
./automation/index.sh 4dn-gene bioindex-dev/4DN/gene-bio/ $env_file
./automation/index.sh 4dn-mondo bioindex-dev/4DN/mondo-bio/ $env_file
./automation/index.sh exrna-gene-counts bioindex-dev/exRNA/gene-counts/ $env_file
./automation/index.sh exrna-rbp-counts bioindex-dev/exRNA/rbp-counts/ $env_file
./automation/index.sh lincs-corr bioindex-dev/lincs/corr/ $env_file
./automation/index.sh diff-exp bioindex-dev/combined_diff_exp/gene/ $env_file
./automation/index.sh diff-exp-phenotype bioindex-dev/combined_diff_exp/phenotype/ $env_file
./automation/index.sh diff-exp-tissue bioindex-dev/combined_diff_exp/tissue/ $env_file
./automation/index.sh pigean-gene-set-phenotype bioindex-dev/catalog/pigean/gene_set/phenotype/ $env_file
./automation/index.sh pigean-gene-set bioindex-dev/catalog/pigean/gene_set/gene_set/ $env_file
./automation/index.sh pigean-gene-phenotype bioindex-dev/catalog/pigean/gene/phenotype/ $env_file
./automation/index.sh pigean-gene bioindex-dev/catalog/pigean/gene/gene/ $env_file
./automation/index.sh pigean-joined-gene bioindex-dev/catalog/pigean/gene_gene_set/gene/ $env_file
./automation/index.sh pigean-joined-gene-set bioindex-dev/catalog/pigean/gene_gene_set/gene_set/ $env_file
./automation/index.sh diff-exp-phenotype-tissue bioindex-dev/combined_diff_exp/phenotype-tissue/ $env_file
./automation/index.sh diff-exp-top-phenotype bioindex-dev/combined_diff_exp/top-phenotype/ $env_file
./automation/index.sh diff-exp-top-tissue bioindex-dev/combined_diff_exp/top-tissue/ $env_file
./automation/index.sh pigean-overall-gene bioindex-dev/catalog/pigean/gene_gene_set/overall_gene/ $env_file
./automation/index.sh pigean-gene-set-source bioindex-dev/catalog/pigean/gene_set/source/ $env_file
./automation/index.sh single-cell-lognorm bioindex-dev/hubmap/single_cell/gene_lognorm/ $env_file
./automation/index.sh diff-exp-top-tissue-phenotype-source bioindex-dev/combined_diff_exp/top-tissue-phenotype-source/ $env_file
./automation/index.sh kids-first-gene-variants bioindex-dev/KidsFirst/variants/gene2/ $env_file
./automation/index.sh glygen-genes bioindex-dev/glygen/glygen/ $env_file
