#!/bin/bash

env_file="bioindex-cancer.env"

./automation/compress.sh global-enrichment bioindex/partitioned_heritability/annotation-tissue/ "${env_file}"
./automation/compress.sh top-associations bioindex/associations/top/trans-ethnic/ "${env_file}"
./automation/compress.sh credible-sets bioindex/credible_sets/locus/trans-ethnic/ "${env_file}"
./automation/compress.sh credible-sets bioindex/credible_sets/locus/ancestry/ "${env_file}"
./automation/compress.sh credible-variants bioindex/credible_sets/variants/trans-ethnic/ "${env_file}"
./automation/compress.sh credible-variants bioindex/credible_sets/variants/ancestry/ "${env_file}"
./automation/compress.sh global-associations bioindex/associations/global/trans-ethnic/ "${env_file}"
./automation/compress.sh ancestry-global-associations bioindex/associations/global/ancestry/ "${env_file}"
./automation/compress.sh gene-finder bioindex/finder/gene/trans-ethnic/ "${env_file}"
./automation/compress.sh gene-finder bioindex/finder/gene/ancestry/ "${env_file}"
./automation/compress.sh ancestry-top-associations bioindex/associations/top/ancestry/ "${env_file}"
./automation/compress.sh genetic-correlation bioindex/genetic-correlation/trans-ethnic/ "${env_file}"
./automation/compress.sh genetic-correlation bioindex/genetic-correlation/ancestry/ "${env_file}"
./automation/compress.sh pathway-associations bioindex/pathway_associations/trans-ethnic/ "${env_file}"
./automation/compress.sh pathway-associations bioindex/pathway_associations/ancestry/ "${env_file}"
./automation/compress.sh huge-phenotype bioindex/huge/phenotype/ "${env_file}"
./automation/compress.sh partitioned-heritability bioindex/partitioned_heritability/trans-ethnic/ "${env_file}"
./automation/compress.sh partitioned-heritability bioindex/partitioned_heritability/ancestry/ "${env_file}"
./automation/compress.sh clumped-variants bioindex/associations/clump/trans-ethnic/ "${env_file}"
./automation/compress.sh ancestry-clumped-variants bioindex/associations/clump/ancestry/ "${env_file}"
./automation/compress.sh c2ct bioindex/credible_sets/c2ct/all/ancestry/ "${env_file}"
./automation/compress.sh c2ct bioindex/credible_sets/c2ct/all/trans-ethnic/ "${env_file}"
./automation/compress.sh c2ct-annotation bioindex/credible_sets/c2ct/annotation/ancestry/ "${env_file}"
./automation/compress.sh c2ct-annotation bioindex/credible_sets/c2ct/annotation/trans-ethnic/ "${env_file}"
./automation/compress.sh c2ct-tissue bioindex/credible_sets/c2ct/tissue/ancestry/ "${env_file}"
./automation/compress.sh c2ct-tissue bioindex/credible_sets/c2ct/tissue/trans-ethnic/ "${env_file}"
./automation/compress.sh c2ct-biosample bioindex/credible_sets/c2ct/biosample/ancestry/ "${env_file}"
./automation/compress.sh c2ct-biosample bioindex/credible_sets/c2ct/biosample/trans-ethnic/ "${env_file}"
./automation/compress.sh c2ct-credible-set bioindex/credible_sets/c2ct/credible_set_id/ancestry/ "${env_file}"
./automation/compress.sh c2ct-credible-set bioindex/credible_sets/c2ct/credible_set_id/trans-ethnic/ "${env_file}"
